Update docs for building TF and reproducing test failures. (#13295)
The workflow is the same, but we're no longer so dependent on using
Bazel or installing importers from the nightly releases.

Tested on Linux and Windows. Windows is strangely broken in TF/Keras and
I can't figure out why:
`ImportError: cannot import name 'deserialize_keras_object' from
partially initialized module 'keras.saving.legacy.serialization' (most
likely due to a circular import)` ([more logs
here](https://gist.github.com/ScottTodd/050ec7f1d8f489e618ef6158e129e853))