Skip mnist_train_test variants when backends or drivers are disabled. (#13019)
Follow-up to https://github.com/openxla/iree/pull/12017, which broke
some (post-submit) macOS builds:
https://github.com/openxla/iree/actions/runs/4662791316/jobs/8253527015#step:7:814
```
 398/1086 Test   #57: iree/tests/e2e/models/mnist_train_test/mnist_train_test_vulkan ***Failed    
ERROR: test_mnist_training (__main__.MnistTrainTest.test_mnist_training)
ValueError: No device found from list ['vulkan']
```